"""add knowledge background jobs

Revision ID: 54e573ed70aa
Revises: 621be94ea91f
Create Date: 2026-09-28 15:41:17.141689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e573ed70aa'
down_revision: Union[str, Sequence[str], None] = '621be94ea91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_jobs_material_id'), 'knowledge_jobs', ['material_id'], unique=False)
    op.create_index(op.f('ix_knowledge_jobs_owner_id'), 'knowledge_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_knowledge_jobs_status'), 'knowledge_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_jobs_trace_id'), 'knowledge_jobs', ['trace_id'], unique=False)
    op.create_index('uq_knowledge_jobs_active_material', 'knowledge_jobs', ['material_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_knowledge_jobs_active_material', table_name='knowledge_jobs', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index(op.f('ix_knowledge_jobs_trace_id'), table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_status'), table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_owner_id'), table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_material_id'), table_name='knowledge_jobs')
    op.drop_table('knowledge_jobs')
    # ### end Alembic commands ###
