"""add trace foundation and scene title

Revision ID: b986fe175725
Revises: 9a46ea51f25d
Create Date: 2026-09-21 14:54:10.127212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b986fe175725'
down_revision: Union[str, Sequence[str], None] = '9a46ea51f25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_trace_id', sa.UUID(), nullable=True),
    sa.Column('trace_type', sa.String(length=64), nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('course_version_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('selected_for_training', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_trace_id'], ['traces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_actor_id'), 'traces', ['actor_id'], unique=False)
    op.create_index(op.f('ix_traces_chapter_id'), 'traces', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_traces_course_id'), 'traces', ['course_id'], unique=False)
    op.create_index(op.f('ix_traces_course_version_id'), 'traces', ['course_version_id'], unique=False)
    op.create_index(op.f('ix_traces_operation'), 'traces', ['operation'], unique=False)
    op.create_index(op.f('ix_traces_parent_trace_id'), 'traces', ['parent_trace_id'], unique=False)
    op.create_index(op.f('ix_traces_scene_id'), 'traces', ['scene_id'], unique=False)
    op.create_index(op.f('ix_traces_status'), 'traces', ['status'], unique=False)
    op.create_index(op.f('ix_traces_trace_type'), 'traces', ['trace_type'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('node', sa.String(length=128), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_events_event_type'), 'trace_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trace_events_trace_id'), 'trace_events', ['trace_id'], unique=False)
    op.create_foreign_key('fk_courses_current_version_id', 'courses', 'course_versions', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('scenes', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'title')
    op.drop_constraint('fk_courses_current_version_id', 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_trace_events_trace_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_event_type'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_traces_trace_type'), table_name='traces')
    op.drop_index(op.f('ix_traces_status'), table_name='traces')
    op.drop_index(op.f('ix_traces_scene_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_parent_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_operation'), table_name='traces')
    op.drop_index(op.f('ix_traces_course_version_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_course_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_chapter_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_actor_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
